## Part 1 : One neuron with 4 inputs, 4 weights, 1 bias

In [ ]:
# 1 neuron with 4 inputs, 4 weights, 1 bias

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

## Part 2: Three neurons with 4 inputs

In [4]:
# 3 neuron with 4 inputs
## each of the 4 inputs is outgoing to 3 neurons
## 3 neurons => 3 unique weight sets (arrays) : w1, w2, w3
## each weight set has four values: w1[val1,val2,val3,val4], w2[val2,val3,val4,val5], w3[val6,val7,val8,val9]
## 3 neurons => 3 biases : bias1, bias2, bias3
## 3 neurons => 3 outputs : output1, output2, output3;
## the combined output of the 3 neurons is an array : output = [output1, output2, output3]

inputs = [1.0, 2.0, 3.0, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

output1 = inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
output2 = inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
output3 = inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3,

output = [output1, output2, output3]
print(output)

[(4.8,), (1.21,), (2.385,)]


### Part 3a : The Dot Product in pure python

In [1]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layer_output = []

# implementation of the dot product   

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0

    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_output.append(neuron_output)

print(layer_output)

[4.8, 1.21, 2.385]


## What is the dot product ?

#### It is the sum of the products of the corresponding entries in two sequences of numbers. It is a scalar (a number), not a vector.

#### Dot product of two vectors a and b :

a = [a1, a2, a3]

b = [b1, b2, b3]

dot product = a1.b1 + a2.b2 + a3.b3

## Implementation of the dot product

#### The Main for loop : `for neuron_weights, neuron_bias in zip(weights, bias) :`

#### It uses two temporary variables (neuron_weights, neuron_bias) to store the weights and biases for each neuron.

> weights = [[0.2, 0.8, -0.5, 1.0],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]

> bias = [2.0, 3.0, 0.5]


<br/><br/>

> Iteration 1 :

*`neuron_weights = [0.2, 0.8, -0.5, 1.0]`*

`neuron_bias = 2.0`

> the neuron_weights[0] and neuron_bias[0] corresponding to neuron 1 are paired up in a tuple : `([0.2, 0.8, -0.5, 1.0], 2.0)`

<br/><br/>

>Iteration 2 :

`neuron_weights = [0.5, -0.91, 0.26, -0.5]`

`neuron_bias = 3.0`

> the neuron_weights[1] and neuron_bias[1] corresponding to neuron 2 are paired up in a tuple : `([0.5, -0.91, 0.26, -0.5], 3.0)`

<br/><br/>

>Iteration 3 : 

`neuron_weights = [-0.26, -0.27, 0.17, 0.87]`

`neuron_bias = 0.5`

> the neuron_weights[2] and neuron_bias[2] corresponding to neuron 3 are paired up in a tuple : `([-0.26, -0.27, 0.17, 0.87], 0.5)`



    ### Nested loop : `for n_input, weight in zip(inputs, neuron_weights) :` 

>Iterates 4 times (one for each input value) over the `inputs` and `neuron_weights` lists simultaneously. 
    >For each iteration :
    
>`n_input` gets one input value from the `inputs` list : `[1.0, 2.0, 3.0, 2.5]`

>`weight` gets the corresponding weight from the `neuron_weights` list : `[0.2, 0.8, -0.5, 1.0]`

>produces the pair `(n_input, weight)` items and multiplies them : `n_input*weight`  
>

<br/><br/>

>Nested loop Iteration 1 :

`neuron_weights = [0.2, 0.8, -0.5, 1.0]`

`n_input = 1.0`, `weight = 0.2` are paired up ->`(1.0, 0.2)` then multiplied : `1.0 * 0.2` -> is added to neuron_output -> `neuron_output += 0.2` 

=> `neuron_output = 0.2`

<br/><br/>

>Nested loop Iteration 2 :

`neuron_weights = [0.2, 0.8, -0.5, 1.0]`

`n_input = 2.0`, `weight = 0.8` are paired up ->`(2.0, 0.8)` then multiplied : `2.0 * 0.8` -> is added to neuron_output -> `neuron_output += 1.6` 

=> `neuron_output = 1.8`

<br/><br/>

>Nested loop Iteration 3 :

`neuron_weights = [0.2, 0.8, -0.5, 1.0]`

`n_input = 3.0`, `weight = -0.5` are paired up ->`(3.0, -0.5)` then multiplied : `3.0 * -0.5` -> is added to neuron_output -> `neuron_output += -1.5` 

=> `neuron_output = 0.3`

<br/><br/>

>Nested loop Iteration 4 :

`neuron_weights = [0.2, 0.8, -0.5, 1.0]`

`n_input = 2.5`, `weight = 1.0` are paired up ->`(2.5, 1.0)` then multiplied : `2.5 * 1.0` -> is added to neuron_output -> `neuron_output += 2.5` 

=> `neuron_output = 2.3`


### Right after the inner for loop, the neuron_output is added to the bias

`neuron_output += neuron_bias` After the inner loop completes, add the neuron's bias to the neuron_output. This completes the calculation for one neuron.


> Iteration 1 :

neuron_output = 0.2 , neuron_bias = 2.0 -> neuron_output += neuron_bias -> neuron_output = 2.2

> Iteration 2 :

neuron_output = 2.2 , neuron_bias = 3.0 -> neuron_output += neuron_bias -> neuron_output = 5.2

> Iteration 3 :

neuron_output = 5.2 , neuron_bias = 0.5 -> neuron_output += neuron_bias -> neuron_output = 5.7

### Add the calculated neuron_output to the layer_output list. This stores the output of each neuron in the layer.

`layer_output.append(neuron_output)`

This code calculates the output of a layer of neurons using matrix multiplication (implemented as nested loops) and then adds the bias terms. The result is a list of outputs, one for each neuron in the layer.

So in our case, the layer_output list will have 3 values : [2.2, 5.2, 5.7]



### Part 3b : The Dot Product using numpy



In [1]:
import sys
import numpy as np
import matplotlib

inputs = [1.0, 2.0, 3.0, 2.5] # a sample of 4 features
weights = [[0.2, 0.8, -0.5, 1.0],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# weights must come first in the dot product function when a matrix is multiplied by a scalar
# the dot product function perform the same operation as the loops in the previous example
# they iterate over the inputs and weights, multiply them and add them to the bias

output = np.dot(weights, inputs) + biases
# np.dot(weights, inputs) = [np.dot(weight[0], inputs), np.dot(weight[1], inputs), np.dot(weight[2], inputs)]
# np.dot(weight[0], inputs) = 0.2*1.0 + 0.8*2.0 + -0.5*3.0 + 1.0*2.5 = 0.2 + 1.6 + -1.5 + 2.5 = 2.8
# np.dot(weight[1], inputs) = 0.5*1.0 + -0.91*2.0 + 0.26*3.0 + -0.5*2.5 = 0.5 + -1.82 + 0.78 + -1.25 = -1.79
# np.dot(weight[2], inputs) = -0.26*1.0 + -0.27*2.0 + 0.17*3.0 + 0.87*2.5 = -0.26 + -0.54 + 0.51 + 2.175 = 1.905

# np.dot(weights, inputs) = [2.8, -1.79, 1.905]

# np.dot(weights, inputs) + biases = [2.8, -1.79, 1.905] + [2.0, 3.0, 0.5] = [4.8, 1.21, 2.405]

print(output)

[4.8   1.21  2.385]


## part 3c : Batches, Layers objects

In [6]:
import numpy as np

# 3x4 matrix of 3 samples of 4 features each (3 different measurements of 4 different sensors)
inputs = [[1.0, 2.0, 3.0, 2.5], # sample 1
          [2.0, 5.0, -1.0, 2.0], # sample 2
          [-1.5, 2.7, 3.3, -0.8]] # sample 3

# layer 1 : 3x4 matrix , 3 neurons with 4 inputs each

weights = [[0.2, 0.8, -0.5, 1.0], # neuron 1 layer 1
           [0.5, -0.91, 0.26, -0.5], # neuron 2
           [-0.26, -0.27, 0.17, 0.87]] # neuron 3

biases = [2.0, 3.0, 0.5] # 1 bias per neuron

# layer 2 : 3x3 matrix , 3 neurons with 3 inputs each   
weights2 = [[0.1, -0.14, 0.5], # neuron 1 layer 2   
            [-0.5, 0.12, -0.33], # neuron 2 layer 2
            [-0.44, 0.73, -0.13]] # neuron 3 layer 2    


biases2 = [-1.0, 2.0, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)



[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# part 4 : Converting layers to objects

In [26]:
import numpy as np

# 3x4 matrix of 3 samples of 4 features each (3 different measurements of 4 different sensors at a given time)
X = [[1.0, 2.0, 3.0, 2.5], # sample 1
     [2.0, 5.0, -1.0, 2.0], # sample 2
     [-1.5, 2.7, 3.3, -0.8]] # sample 3

# initializing weights randomly
np.random.seed(0)

#layer constructor
class Layer_Dense:
    
    # layer initialization (where 'n_inputs'= number of inputs and features, and 'n_neurons'= number of neurons of our choosing)
    def __init__(self, n_inputs,n_neurons):
       
        # 'n_neurons' sets of weights of n_inputs features are initialized with a small random number
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # !! inverting the shape of weights (4x3 instead of 3x4) avoids us having to transpose it during fwd pass
        
        # 'n_neurons' biases are initialized to zero
        self.biases = np.zeros((1,n_neurons)) # !! the parameter is a tuple representing the shape of the biases matrix, it must be surrounded by parenthesis
    
    # the fwd method takes the 'n_inputs' inputs (training data or output of previous layer)
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5) # layer 1 initialization. we choose 'n_neurons' = 5 and 'n_inputs' is derived from the input data X shape (4, )
# => 5 sets of weights of 4 features are initialized with a small random number
# => 1 set of 5 biases are initialized to zero

# the fwd method takes the 4 inputs of the training data and performs the dot product inputs.dot(weights) and adds the biases
layer1.forward(X)

print("Layer1 inputs is a matrix (a batch of samples) with a shape (dimensions) of " + str(np.array(X).shape))
print(X)
print("Type of Layer1 inputs is " + str(type(X)))

print('\n')

print("Layer1Randomly initialized weights is a matrix with a shape (dimensions) of:" + str(np.array(layer1.weights).shape))
print(layer1.weights)

print('\n')

print("Layer1 Biases is a matrix with a shape (dimensions) of:" + str(np.array(layer1.biases).shape))
print(layer1.biases)

print('\n')

print("Layer1 output is a matrix with a shape (dimensions) of:" + str(np.array(layer1.output).shape))
print(layer1.output)

print('\n')

layer2 = Layer_Dense(5,2) # layer 2 initialization. we choose 'n_neurons' = 2 and 'n_inputs' is derived from the number of neurons of the previous layer (5)
# => 2 sets of weights of 5 features are initialized with a small random number
# => 1 set of 2 biases are initialized to zero

# the fwd method takes the 5 inputs of the training data and performs the dot product inputs.dot(weights) and adds the biases
layer2.forward(layer1.output)

print("Layer2 inputs is a matrix with a shape (dimensions) of " + str(np.array(layer1.output).shape))
print(layer1.output)
print("Type of layer2 inputs is " + str(type(layer1.output)))

print('\n')

print("Layer2 Randomly initialized weights is a matrix with a shape (dimensions) of:" + str(np.array(layer2.weights).shape))
print(layer2.weights)

print('\n')

print(" Layer2 biases is a matrix with a shape (dimensions) of:" + str(np.array(layer2.biases).shape))
print(layer2.biases)

print('\n')

print("Layer2 output is a matrix with a shape (dimensions) of:" + str(np.array(layer2.output).shape))
print(layer2.output)




X is a matrix (a batch of samples) with a shape (dimensions) of (3, 4)
[[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
Type of X is <class 'list'>


Randomly initialized weights is a matrix with a shape (dimensions) of:(4, 5)
[[ 0.17640523  0.04001572  0.0978738   0.22408932  0.1867558 ]
 [-0.09772779  0.09500884 -0.01513572 -0.01032189  0.04105985]
 [ 0.01440436  0.14542735  0.07610377  0.0121675   0.04438632]
 [ 0.03336743  0.14940791 -0.02051583  0.03130677 -0.08540957]]


Biases is a matrix with a shape (dimensions) of:(1, 5)
[[0. 0. 0. 0. 0.]]


Layer 1 output is a matrix with a shape (dimensions) of:(3, 5)
[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


Layer2 inputs is a matrix (a batch of samples) with a shape (dimensions) of (3, 5)
[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.708